name: Build and Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 17.x
          
      - name: Install dependencies with yarn
        run: yarn
        
      - name: Build production site bundle
        run: yarn build
        
      - name: Upload as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: public
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "jb3/infra"

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: build
          path: build
          
      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH }}
          ssh-host: ${{ secrets.DEPLOY_HOST }}
          ssh-port: 22
          

      - name: Deploy blog playbook
        uses: tomasnorre/ansible-cli-client@0.0.2
        with:
          command: ansible-playbook -i inventory playbook.yml -t blog
