name: Build and Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 17.x
          
      - name: Install dependencies with yarn
        run: yarn
        
      - name: Build production site bundle
        run: yarn build
        
      - name: Upload as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: public
