name: Build and Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 17.x
          
      - name: Install dependencies with yarn
        run: yarn
        
      - name: Build production site bundle
        run: yarn build
        
      - name: Upload as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: public
          
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "jb3/infra"

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: build
          path: build

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        with:
          playbook: playbook.yml
          key: ${{ secrets.DEPLOY_SSH }}
          options: |
            -i inventory
            --limit web
            -t blog
